coverage:
  status:
    project:
      default: false
      ai:
        target: 100.0
        flags:
          - ai
        paths:
          - ^packages/ai/.*
comment:
  require_changes: true
flags:
  ai:
    paths:
      - ^packages/ai/.*
