parameters:
  path: ''
  version: 0.12.17
steps:
  - bash: |
      if [[ -z "${{ parameters.path }}" ]]; then
        echo '##vso[task.logissue type=error;]Missing template parameter "path"'
        echo '##vso[task.complete result=Failed;]DONE'
      fi
    displayName: Check for required parameters
  - script: pip install --upgrade pip poetry==${{ parameters.version }}
    displayName: Install Poetry
  - script: poetry config settings.virtualenvs.path ${{ parameters.path }}
    displayName: Configure Poetry
